clear all;close all;clc;
Before=imread('clock2.gif');
Back=imread('clock1.gif');
ZJ1=imadd(Before,-80);
ZJ2=imadd(Back,-80);
result1=imadd(Back,Before);
result2=imadd(Back,ZJ1);
result3=imadd(ZJ2,Before);
% imwrite(ZJ1,'°µÇ°¾°Í¼.jpg');
% imwrite(ZJ2,'°µ±³¾°Í¼.jpg');
% imwrite(result1,'Ç°¾Û½¹µþ¼Óºó¾Û½¹.jpg');
% imwrite(result2,'°µÇ°¾°µþ¼Óºó¾Û½¹.jpg');
% imwrite(result3,'°µ±³¾°µþ¼ÓÇ°¾Û½¹.jpg');
subplot(231),imshow(Before),title('Ç°¾Û½¹Í¼');
subplot(232),imshow(Back),title('ºó¾Û½¹Í¼');
subplot(233),imshow(ZJ2),title('°µÇ°¾°Í¼');
subplot(234),imshow(result1),title('Ç°¾Û½¹µþ¼Óºó¾Û½¹');
subplot(235),imshow(result3),title('°µ±³¾°µþ¼ÓÇ°¾Û½¹');
subplot(236),imshow(result2),title('°µÇ°¾°µþ¼Óºó¾Û½¹');
