clear all;close all;clc;
Image=imread('house.png');
Image=rgb2gray(Image);
BW= edge(Image,'roberts');
H1=[1 0; 0 -1];
H2=[0 1;-1 0];
R1=imfilter(Image,H1);
R2=imfilter(Image,H2);
edgeImage=abs(R1)+abs(R2);
sharpImage=Image+edgeImage;
subplot(221),imshow(Image),title('Ô­Ê¼Í¼Ïñ');
subplot(222),imshow(BW),title('±ßÔµ¼ì²â');
subplot(223),imshow(edgeImage),title('RobertÌÝ¶ÈÍ¼Ïñ');
subplot(224),imshow(sharpImage),title('RobertÈñ»¯Í¼Ïñ');
% imwrite(BW,'robertBW.jpg');
% imwrite(Image,'Ô­Ê¼Í¼Ïñ.jpg');
% imwrite(BW,'±ßÔµ¼ì²â.jpg');
% imwrite(edgeImage,'RobertÌÝ¶ÈÍ¼Ïñ.jpg');
% imwrite(Image,'RobertÈñ»¯Í¼Ïñ.jpg');
